name: 功能建议
description: 我希望 Bookwise Reader 增加这个功能
labels: 'feature request'
body:
  - type: checkboxes
    id: testing0
    attributes:
      label: 我已经搜索了 Issue 列表，没有找到类似的需求
      options:
        - label: 'Yes'
          required: true

  - type: checkboxes
    id: testing1
    attributes:
      label: 我已经试用最新开发版，同样没找到这个功能
      options:
        - label: 'Yes'
          required: true

  - type: checkboxes
    id: testing2
    attributes:
      label: 如果您有不止一个需求，请在多个 issue 里分别提交.
      options:
        - label: 'Yes'
          required: true

  - type: textarea
    id: introduction
    attributes:
      label: 简单介绍
      placeholder: 关于这个需求的简单介绍
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: 细节描述
      placeholder: 关于这个需求的细节描述
    validations:
      required: true
